### ISSUE TITLE
Move to KDE 6

### ISSUE THREAD

**Issue by bouteillerAlan** [bouteillerAlan/blurredwallpaper#25]
See ~#26~ #36  

Todo : 

- [x] the blur doesn't work - line 75 in `main.qml` 
- [x] the blur doesn't work on the preview - line 109 in `WallpaperDelegate.qml`
- [x] deploy to the AUR

For this one, I have to implement the same behavior has when the user switch between `layout: Folder view` and `Layout: background` in the wallpaper settings : 
- [ ] when we switch from the singleImage to the slideShow the img list is not updated #33 #31 #35 

For this two, maybe use `TaskManager.TasksModel` [[l](https://github.com/kupiqu/plasma-active-application/blob/1a81d8a9eb495979da4e2c522519512c016e2e8d/contents/ui/main.qml#L46C5-L46C27)] :
- [x] certain window is not detected (like plasmoid settings for example) #32
- [x] the blur doesn't go away on close #32

**Comment by dr460nf1r3** [comment]
Hi! I'm trying this widget using Archs KDE 6 builds from `extra-testing`. It doesn't show up as wallpaper choice even though being packaged (https://aur.archlinux.org/packages/plasma6-wallpapers-blurredwallpaper). Any idea why this might be?

**Comment by bouteillerAlan** [comment]
@dr460nf1r3 

Hey, sorry for the mess, like I said I have updated the package on the AUR a little too soon because plasma 6 is still on testing on the extra repository. Because of that, I have screwed up the package this morning, my bad for that ^^

So now we have two packages available in function of your plasma version :
 - for plasma 5 : [kdeplasma5-blurredwallpaper-git](https://aur.archlinux.org/packages/kdeplasma5-blurredwallpaper-git)
  - for plasma 6 : [kdeplasma-blurredwallpaper-git](https://aur.archlinux.org/packages/kdeplasma-blurredwallpaper-git)

Keep me in touch if everything is back to normal :)

**Comment by dr460nf1r3** [comment]
Funny thing - I found this out when you posted it - I packaged this plasmoid too (https://aur.archlinux.org/packages/plasma6-wallpapers-blurredwallpaper). Since yours are `-git` and mine is stable, that should be fine though. It seems to be working now, thanks! :)

**Comment by bouteillerAlan** [comment]
@dr460nf1r3 no problem :)

**Comment by bouteillerAlan** [comment]
Check the last two in #39

**Comment by easyteacher** [comment]
For slideshow can anyone test https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/4798 ?
